function-future/function-backend

function-app/pom.xml, function-app/src/main/resources/application-local.properties, function-app/src/main/resources/application-no-mock.properties, function-service-api/pom.xml, function-service-api/src/main/java/com/future/function/service/api/feature/core/MailService.java, function-service-impl/pom.xml, function-service-impl/src/main/java/com/future/function/service/impl/feature/core/MailServiceImpl.java, function-service-impl/src/main/java/com/future/function/service/impl/feature/core/UserServiceImpl.java, function-service-impl/src/test/java/com/future/function/service/impl/feature/core/MailServiceImplTest.java, function-service-impl/src/test/java/com/future/function/service/impl/feature/core/UserServiceImplTest.java
=> [feature/CORE-72] Send email to newly-registered user

function-service-impl/src/main/java/com/future/function/service/impl/feature/scoring/QuizServiceImpl.java, function-service-impl/src/test/java/com/future/function/service/impl/feature/scoring/QuizServiceImplTest.java
remove create student quiz for create and copy quiz
#269
=> remove create student quiz for create and copy quiz

function-validation/src/main/java/com/future/function/validation/validator/core/FileMustBeImageValidator.java
=> [bugfix/CORE-78] NPE when creating/updating user with random avatar id

function-data-migration/src/main/java/com/future/function/data/migration/change/log/DataMigration_018.java
=> [bugfix/CORE-81] Change login modal urlRegex

function-app/src/main/java/com/future/function/FunctionApplication.java, function-app/src/main/resources/application-local.properties, function-app/src/main/resources/application-no-mock.properties, function-common/src/main/java/com/future/function/common/properties/core/FunctionProperties.java, function-service-impl/src/main/java/com/future/function/service/impl/feature/core/MailServiceImpl.java, function-service-impl/src/main/java/com/future/function/service/impl/feature/core/UserServiceImpl.java, function-service-impl/src/test/java/com/future/function/service/impl/feature/core/MailServiceImplTest.java, function-service-impl/src/test/java/com/future/function/service/impl/feature/core/UserServiceImplTest.java
=> [bugfix/CORE-79] Make send email async & refactor mail service

function-data-migration/src/main/java/com/future/function/data/migration/change/log/DataMigration_019.java
Fixes #293 
* Add mobile profile, account access list, edit batches access list, and edit menu list
=> [feature/CORE-82] Add access lists and menu list

function-service-api/src/main/java/com/future/function/service/api/feature/scoring/StudentQuizService.java, function-service-impl/src/main/java/com/future/function/service/impl/feature/scoring/StudentQuizServiceImpl.java, function-service-impl/src/test/java/com/future/function/service/impl/feature/scoring/StudentQuizServiceImplTest.java, function-web/src/main/java/com/future/function/web/controller/scoring/StudentQuestionController.java, function-web/src/main/java/com/future/function/web/mapper/response/scoring/StudentQuizDetailResponseMapper.java, function-web/src/test/java/com/future/function/web/controller/scoring/StudentQuestionControllerTest.java, function-web/src/test/java/com/future/function/web/mapper/response/scoring/StudentQuizDetailResponseMapperTest.java
=> Scoring 7 create time limit endpoint

function-common/src/main/java/com/future/function/common/data/core/SharedCourseData.java, function-repository/src/main/java/com/future/function/repository/feature/core/CourseRepository.java, function-repository/src/test/java/com/future/function/repository/feature/core/CourseRepositoryTest.java, function-service-impl/src/main/java/com/future/function/service/impl/feature/core/SharedCourseServiceImpl.java, function-service-impl/src/test/java/com/future/function/service/impl/feature/core/SharedCourseServiceImplTest.java, function-validation/src/main/java/com/future/function/validation/annotation/core/CourseMustExist.java, function-validation/src/main/java/com/future/function/validation/validator/core/CourseMustExistValidator.java, function-validation/src/test/java/com/future/function/validation/dummy/SharedCourseDummyData.java, function-validation/src/test/java/com/future/function/validation/validator/core/CourseMustExistValidatorTest.java, function-web-model/src/main/java/com/future/function/web/model/request/core/SharedCourseWebRequest.java
=> [bugfix/CORE-83] Fix unable to share course from batch to batch

function-app/src/main/resources/application-no-mock.properties
=> fix no-mock properties

.github/workflows/install_and_sonarcloud.yml, pom.xml
=> [feature/CI] Setup CI and Sonarcloud Analysis

function-repository/pom.xml, function-repository/src/main/java/com/future/function/repository/listener/core/BatchMongoEventListener.java, function-repository/src/test/java/com/future/function/repository/listener/core/BatchMongoEventListenerTest.java, function-service-api/src/main/java/com/future/function/service/api/feature/core/ResourceService.java, function-service-impl/src/main/java/com/future/function/service/impl/feature/core/ResourceServiceImpl.java, function-service-impl/src/main/java/com/future/function/service/impl/feature/core/SharedCourseServiceImpl.java, function-service-impl/src/test/java/com/future/function/service/impl/feature/core/ResourceServiceImplTest.java, function-service-impl/src/test/java/com/future/function/service/impl/feature/core/SharedCourseServiceImplTest.java, pom.xml
=> [bugfix/CORE-75] Delete students and shared courses when batch is deleted

function-validation/src/main/java/com/future/function/validation/validator/core/FileMustBeImageValidator.java, function-validation/src/test/java/com/future/function/validation/validator/core/FileMustBeImageValidatorTest.java
=> [bugfix/CORE-84] NPE on FileMustBeImageValidator if file is not found on repository

function-service-impl/src/main/java/com/future/function/service/impl/feature/core/ActivityBlogServiceImpl.java, function-service-impl/src/test/java/com/future/function/service/impl/feature/core/ActivityBlogServiceImplTest.java
=> [bugfix/CORE-85] Check validation of userId on getting activity blogs by specific user id

function-web/src/main/java/com/future/function/web/controller/core/UserController.java, function-web/src/main/java/com/future/function/web/mapper/request/core/UserRequestMapper.java, function-web/src/test/java/com/future/function/web/controller/core/UserControllerTest.java, function-web/src/test/java/com/future/function/web/mapper/request/core/UserRequestMapperTest.java
=> [bugfix/CORE-76] Prevent admin to delete himself while logged in

function-service-impl/src/test/java/com/future/function/service/impl/feature/core/ResourceServiceImplTest.java
=> [bugfix/CORE-86] Fix ResourceServiceImplTest to be able to run on any OS

.github/workflows/sonarcloud.yml, pom.xml
The previous run command cannot scan code coverage. This commit fixed such problem and also renamed actions file.
=> Change run command and rename actions file

function-service-impl/src/main/java/com/future/function/service/impl/feature/core/ActivityBlogServiceImpl.java, function-service-impl/src/test/java/com/future/function/service/impl/feature/core/ActivityBlogServiceImplTest.java
=> [bugfix/CORE-87] Empty page on no passed userId for activity blogs

function-web/src/main/java/com/future/function/web/mapper/request/core/UserRequestMapper.java, function-web/src/test/java/com/future/function/web/mapper/request/core/UserRequestMapperTest.java
=> [bugfix/CORE-88] Incorrect result from validateNotLoggedInUser

function-service-impl/src/main/java/com/future/function/service/impl/feature/core/SharedCourseServiceImpl.java, function-service-impl/src/test/java/com/future/function/service/impl/feature/core/SharedCourseServiceImplTest.java
=> [bugfix/CORE-90] NPE on creating course file copy

function-data-migration/src/main/java/com/future/function/data/migration/change/log/DataMigration_021.java, function-web/src/main/java/com/future/function/web/mapper/request/core/UserRequestMapper.java, function-web/src/test/java/com/future/function/web/mapper/request/core/UserRequestMapperTest.java
=> [bugfix/CORE-89] Add and change new courses route path access list

function-service-api/src/main/java/com/future/function/service/api/feature/core/SharedCourseService.java, function-service-impl/src/main/java/com/future/function/service/impl/feature/core/SharedCourseServiceImpl.java, function-service-impl/src/test/java/com/future/function/service/impl/feature/core/SharedCourseServiceImplTest.java, function-web/src/main/java/com/future/function/web/controller/core/SharedCourseController.java, function-web/src/test/java/com/future/function/web/controller/core/SharedCourseControllerTest.java
=> [bugfix/CORE-91] Prevent non-batch student from accessing other batches' shared courses data

function-data-migration/src/main/java/com/future/function/data/migration/change/log/DataMigration_021.java, function-data-migration/src/main/java/com/future/function/data/migration/change/log/DataMigration_022.java
=> add new access lists

docs/API/core/batches-api.md, function-repository/src/main/java/com/future/function/repository/feature/core/BatchRepository.java, function-repository/src/test/java/com/future/function/repository/feature/core/BatchRepositoryTest.java, function-service-api/src/main/java/com/future/function/service/api/feature/core/BatchService.java, function-service-impl/src/main/java/com/future/function/service/impl/feature/core/BatchServiceImpl.java, function-service-impl/src/test/java/com/future/function/service/impl/feature/core/BatchServiceImplTest.java, function-web/src/main/java/com/future/function/web/controller/core/BatchController.java, function-web/src/main/java/com/future/function/web/mapper/response/core/BatchResponseMapper.java, function-web/src/test/java/com/future/function/web/controller/core/BatchControllerTest.java, function-web/src/test/java/com/future/function/web/mapper/response/core/BatchResponseMapperTest.java
=> [feature/CORE-94] Change get batches return type to List

function-data-migration/src/main/java/com/future/function/data/migration/change/log/DataMigration_021.java
=> [bugfix/CORE-92] Fix ChangeLog order

function-validation/src/main/java/com/future/function/validation/annotation/scoring/ExtensionMustBeValid.java, function-validation/src/main/java/com/future/function/validation/validator/scoring/ExtensionMustBeValidValidator.java, function-validation/src/test/java/com/future/function/validation/validator/scoring/ExtensionMustBeValidValidatorTest.java, function-web-model/src/main/java/com/future/function/web/model/request/scoring/AssignmentWebRequest.java
=> add validation extension

function-data-migration/src/main/java/com/future/function/data/migration/change/log/DataMigration_002.java, function-data-migration/src/main/java/com/future/function/data/migration/change/log/DataMigration_025.java, function-model/src/main/java/com/future/function/model/entity/feature/core/FileV2.java, function-model/src/main/java/com/future/function/model/entity/feature/core/embedded/FilePath.java, function-service-api/src/main/java/com/future/function/service/api/feature/core/FileService.java, function-service-impl/src/main/java/com/future/function/service/impl/feature/core/FileServiceImpl.java, function-service-impl/src/test/java/com/future/function/service/impl/feature/core/FileServiceImplTest.java, function-web/src/main/java/com/future/function/web/mapper/response/core/FileResponseMapper.java, function-web/src/test/java/com/future/function/web/controller/core/FileControllerTest.java, function-web/src/test/java/com/future/function/web/mapper/response/core/FileResponseMapperTest.java
=> [feature/CORE-96] Refactor file/folder path database storage implementation

function-service-impl/src/main/java/com/future/function/service/impl/feature/core/scheduler/FileDeleteScheduler.java, function-service-impl/src/test/java/com/future/function/service/impl/feature/core/scheduler/FileDeleteSchedulerTest.java
=> [bugfix/CORE-95] FileDeleteScheduler not deleting file versions

function-data-migration/src/main/java/com/future/function/data/migration/change/log/DataMigration_023.java, function-data-migration/src/main/java/com/future/function/data/migration/change/log/DataMigration_026.java, function-data-migration/src/main/java/com/future/function/data/migration/constant/IndexName.java, function-repository/src/main/java/com/future/function/repository/feature/core/UserRepository.java, function-repository/src/main/java/com/future/function/repository/listener/core/BatchMongoEventListener.java, function-repository/src/test/java/com/future/function/repository/feature/core/UserRepositoryTest.java, function-service-api/src/main/java/com/future/function/service/api/feature/core/UserService.java, function-service-impl/src/main/java/com/future/function/service/impl/feature/core/UserServiceImpl.java, function-service-impl/src/test/java/com/future/function/service/impl/feature/core/UserServiceImplTest.java, function-web/src/main/java/com/future/function/web/controller/core/UserController.java, function-web/src/test/java/com/future/function/web/controller/core/UserControllerTest.java
=> [feature/CORE-93] Add filter per batch on user page student's tab

function-validation/src/main/java/com/future/function/validation/validator/scoring/ExtensionMustBeValidValidator.java
=> to lower case extension

function-service-impl/src/main/java/com/future/function/service/impl/feature/scoring/AssignmentServiceImpl.java, function-service-impl/src/main/java/com/future/function/service/impl/feature/scoring/RoomServiceImpl.java, function-service-impl/src/main/java/com/future/function/service/impl/feature/scoring/StudentQuestionServiceImpl.java, function-service-impl/src/main/java/com/future/function/service/impl/feature/scoring/StudentQuizServiceImpl.java
=> fix wrong order of flow
